name: coolchat
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.0.5
  flutter_native_splash: ^2.3.1
  shared_preferences: ^2.2.0
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  cached_network_image: ^3.2.3
  http: ^1.1.0
  intl: ^0.19.0
  timezone: ^0.9.2
  url_launcher: ^6.1.14
  flutter_linkify: ^6.0.0
  flutter_html: ^3.0.0-beta.2
  selectable_autolink_text: ^2.6.0
  permission_handler: ^11.0.0
  flutter_cache_manager: ^3.3.1
  cached_network_image_platform_interface: ^4.0.0
  web_socket_channel: ^3.0.0
  beholder_flutter: ^0.3.0+2
  connectivity: ^3.0.6
  gif: ^2.3.0
  flutter_secure_storage: ^9.2.2
  flutter_local_notifications: ^16.3.2
  scrollable_positioned_list: ^0.3.8
  file_picker: ^8.0.0+1
  device_info: ^2.0.3
  image_picker: ^1.0.8
  photo_view: ^0.14.0
  dio: ^5.4.2+1
  path_provider: ^2.1.2
  image_cropper: ^5.0.1
  flutter_beep: ^1.0.0
  open_file: ^3.3.2
  flutter_sound: ^9.2.13
  camera: ^0.10.6
  video_player: ^2.8.6
  infinite_carousel: ^1.1.1

dev_dependencies:
  flutter_vibrate: ^1.3.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  assets:
    - assets/images/
    - assets/animation/
    - assets/l10n/
    - assets/sounds/

  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-Regular.ttf

  uses-material-design: true

 
